"""empty message

Revision ID: ca15697198f8
Revises: 
Create Date: 2023-11-04 01:06:11.213973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca15697198f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dim$position')
    op.drop_table('crew')
    op.drop_constraint('tech_supp_fk', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'dim_position', ['position_id'], ['id'])
    op.alter_column('purchase_ticket', 'purchase_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.add_column('tickets', sa.Column('class_type', sa.String(length=10), nullable=True))
    op.drop_column('tickets', 'class')
    op.drop_constraint('work_schedule_fk_crew_tabelnum_fk', 'work_schedule', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('work_schedule_fk_crew_tabelnum_fk', 'work_schedule', 'crew', ['employee_tabelnum'], ['tabelnum'])
    op.add_column('tickets', sa.Column('class', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'class_type')
    op.alter_column('purchase_ticket', 'purchase_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('tech_supp_fk', 'employee', 'dim$position', ['position_id'], ['id'])
    op.create_table('crew',
    sa.Column('tabelnum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['dim$position.id'], name='crew_fk', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tabelnum', name='crew_pk')
    )
    op.create_table('dim$position',
    sa.Column('position_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"dim$position_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dim$position_pk')
    )
    op.drop_table('dim_position')
    # ### end Alembic commands ###
